// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // .env has no separate dev database — DATABASE_URL points straight at
    // production. shadowDatabaseUrl scopes migration diffing to its own
    // schema on the same instance (see CLAUDE.md's migration workflow) so
    // `migrate diff` never touches `public`.
    shadowDatabaseUrl: `${process.env["DIRECT_URL"]}&schema=migrate_scratch`,
  },
});
